language: python

# Run jobs on container-based infrastructure, can be overridden per job

matrix:
  include:
#   # Extra includes for OSX since python language is not available by default on OSX
#   - os: osx
#     language: generic
#     env: PYTHON_VER=3.6
#   - os: osx
#     language: generic
#     env: PYTHON_VER=3.7


    - os: linux
      language: generic  # No need to set Python version since its conda
      env: PYTHON_VER=3.6
    - os: linux
      language: generic
      env: PYTHON_VER=3.7

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

before_install:
  # Install the Python environment
  - source devtools/travis-ci/before_install.sh
  - python -V
install:
    # Create test environment for package
  - python devtools/scripts/create_conda_env.py -n=test -p=$PYTHON_VER devtools/conda-envs/test_env.yaml
    # Activate the test environment
  - conda activate test
    # Build and install package
  - pip install numpy
  - pip install scipy
  - pip install nose
  - pip install pybind11
  - mkdir build
  - cd build
  - cmake ..
  - cd ..
  - python setup.py build_ext --inplace
script:
  - python -m pytest --ignore=lib/pybind11

notifications:
    email: false

after_success:
  - codecov
